# numpy. random package
This jupyter notebook contains the numpy.random package investigation as part of the Programming for Data Analysis Module of Data Analytics at GMIT.

In [1]:
import numpy as np

# random.rand function
__numpy.random.rand(d0, d1, …, dn)__
<br>
&nbsp;&nbsp; Create an array of the given shape and populate it with random samples from a uniform distribution over (0,1)

d0, d1, …, dn .....(int)optional <br>
&ensp; The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.


In [6]:
np.random.rand() # if no dimention is given a random float value between 0 - 1

0.37103626147724045

In [3]:
np.random.rand(7)#create a one dimentional array of size 7 and each element vale lie between 0 - 1

array([0.3102102 , 0.98064643, 0.94906879, 0.23334678, 0.52969916,
       0.02362513, 0.50369608])

In [4]:
np.random.rand(2,3)# two dimentional array

array([[0.47292442, 0.43779127, 0.29507988],
       [0.54385811, 0.44657601, 0.81208594]])

In [5]:
np.random.rand (3,2,4) # three dimention array

array([[[0.5087001 , 0.41010529, 0.98303576, 0.7644716 ],
        [0.70508132, 0.74353531, 0.02622298, 0.81092891]],

       [[0.29393357, 0.15689284, 0.48013498, 0.18455235],
        [0.97840196, 0.82819963, 0.14003826, 0.61205017]],

       [[0.71869668, 0.03332611, 0.00513341, 0.76772461],
        [0.65253493, 0.54082637, 0.37285153, 0.73080526]]])