# numpy. random package
This jupyter notebook contains the numpy.random package investigation as part of the Programming for Data Analysis Module of Data Analytics at GMIT.

In [1]:
import numpy as np #import numpy

# Simple Random Data

# random.rand function
__numpy.random.rand(d0, d1, …, dn)__
<br>
&nbsp;&nbsp; Create an array of the given shape and populate it with random samples from a uniform distribution over (0,1)

d0, d1, …, dn .....(int)optional <br>
&ensp; The dimensions of the returned array, should all be positive. If no argument is given a single Python float is returned.


In [2]:
np.random.rand() # if no dimention is given a random float value between 0 - 1

0.18999253980797637

In [3]:
np.random.rand(7)#create a one dimentional array of size 7 and each element value lie between 0 - 1

array([0.46716909, 0.85291745, 0.35266088, 0.404497  , 0.01652909,
       0.97234225, 0.28572147])

In [4]:
np.random.rand(2,3)# two dimentional array

array([[0.47501437, 0.46784195, 0.50565088],
       [0.04795754, 0.82592279, 0.49758109]])

In [5]:
np.random.rand (3,2,4) # three dimention array

array([[[0.319913  , 0.88748943, 0.89713012, 0.64905114],
        [0.82506501, 0.22522528, 0.81256328, 0.87699117]],

       [[0.76891927, 0.24539406, 0.87166104, 0.74881692],
        [0.29220432, 0.28632455, 0.74544585, 0.79222503]],

       [[0.53277841, 0.31825924, 0.48967375, 0.15478294],
        [0.18992193, 0.88344449, 0.89651239, 0.23171935]]])

# numpy.random.randint(low[,high, size, dtype]) 
Return random integers from low (inclusive) to high (exclusive).

In [6]:
np.random.randint(5,15) # generate a random number between 5 - 14

6

In [7]:
np.random.randint(5,15,5) # generate an array of 5 random numbers between values 5- 14 (inclusive)

array([ 8, 14,  9,  8,  7])

In [8]:
np.random.randint(5,15,[5,5])# generate two dimentional array(5 x 5)of random numbers between values 5- 14 (inclusive)

array([[ 5,  9,  8, 11,  8],
       [ 9,  9,  6, 13, 14],
       [10,  6, 14, 11,  5],
       [ 5,  9,  7,  5, 14],
       [13,  7,  9,  5, 14]])

In [12]:
np.random.randint(5,15,size=(5,5))# generate two dimentional array(5 x 5)of random numbers between values 5- 14 (inclusive)

array([[ 7,  8,  8, 14,  5],
       [13, 11,  6,  6,  6],
       [ 5,  7, 12, 14, 14],
       [12, 14, 11,  9, 11],
       [12,  6, 10,  7,  9]])

# numpy.random.permutation
numpy.random.permutation(x)
Randomly permute a sequence, or return a permuted range.

If x is a multi-dimensional array, it is only shuffled along its first index.

In [13]:
a=np.random.randint(5,15,8)

In [15]:
print (a)

[14 12  5 14 14 13  5  7]


In [16]:
np.random.permutation(a)

array([ 7, 13, 14, 14,  5, 14, 12,  5])

In [21]:
b= np.random.randint(4,10,size=(3,4))
print(b)

[[8 5 9 5]
 [7 8 4 9]
 [5 9 9 9]]


In [22]:
c= np.random.permutation(b)
print(c)

[[5 9 9 9]
 [7 8 4 9]
 [8 5 9 5]]


here above its clear that rows are shuffled positons but the contents in row are not shuffled